# Generated by Django 5.2.14 on 2026-06-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_rename_paid_amount_invoice_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('ONLINE', 'Online'), ('CREDIT', 'Credit'), ('UPI', 'UPI')], default='CASH', max_length=20),
        ),
    ]
