# Generated by Django 5.2.14 on 2026-06-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Vighnaharta Fataka', max_length=255)),
                ('address', models.TextField(default='Shop No. 1, Main Road')),
                ('phone', models.CharField(default='9876543210', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_message', models.TextField(default='Thank you for your business!')),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
