# Generated by Django 5.2.14 on 2026-06-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='dashboard_password',
            field=models.CharField(blank=True, help_text='Password to access the dashboard tab in the app', max_length=50, null=True),
        ),
    ]
