# Generated by Django 5.2.14 on 2026-06-15 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companysettings_dashboard_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='dashboard_password',
        ),
        migrations.AddField(
            model_name='companysettings',
            name='dashboard_pin_hash',
            field=models.CharField(blank=True, help_text='Hashed dashboard PIN. Never store raw PIN.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='pin_failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='pin_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DashboardAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Access Token',
                'verbose_name_plural': 'Dashboard Access Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
