# Generated by Django 5.2.14 on 2026-06-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cent_in_per_cs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='no_of_case',
            field=models.IntegerField(default=0),
        ),
    ]
