# Generated by Django 5.2.17 on 2026-08-13 14:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_cent_in_per_cs_product_no_of_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cent_in_per_cs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
