# Generated by Django 5.2.17 on 2026-08-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_cent_in_per_cs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='entry_mode',
            field=models.CharField(choices=[('cent', 'Cent'), ('piece', 'Piece')], default='cent', max_length=10),
        ),
    ]
